Add OpenSSL support
tmccombs/tls-listener pull request #21
Opened 2022-03-20 14:16 UTC by jacob-pro

I just discovered native-tls doesn't support client certificate verification :(

https://github.com/sfackler/rust-native-tls/issues/161

So I need to use openssl instead, fortunately your trait design has made this very easy @tmccombs  :)

2022-03-21 07:27 UTC, tmccombs requested changes
There are some conflicts that need to be resolved.

2022-03-21 10:11 UTC, jacob-pro commented on src/net.rs
> +use tokio::net::{TcpListener, TcpStream};
If you merge your PR - then I will rebase this one?

2022-03-21 22:18 UTC, jacob-pro commented on src/net.rs
> +use tokio::net::{TcpListener, TcpStream};
Rebased and squashed, conflicts should be resolved.

2022-03-22 05:26 UTC, tmccombs approved these changes

2022-03-22 05:26 UTC, merged